### ISSUE TITLE
Bookmark Sea Creatures

### ISSUE THREAD

**Issue by cat-miller** [cat-miller/capstone-project#14]
### Value Description

As a User
I want *to bookmark the Sea Creatures I caught*
so that *I can see my progress in the game*

### Description

<img width="316" alt="Screenshot 2022-05-24 at 10 08 53" src="https://user-images.githubusercontent.com/99614110/171600366-62c4a126-bc4f-4a59-934c-34a1a211d790.png">

### Acceptance Criterea

- [x] there should be a bookmark button on each ```SeaCreatureCard```
- [x] there should be a bookmark button on each ```SeaCreatureDetailedCard```
- [x] it should mark all sea creatures I caught
- [x] there should be a counter on the top near the headline

### Tasks

- [x]  create a new branch
- [x] create a ```IconButton```
- [x] create a ```TotalCount``` component
- [x] add styling
- [x] add logic
