### ISSUE TITLE
Bookmark Sea Creatures that were donated to the Museum 

### ISSUE THREAD

**Issue by cat-miller** [cat-miller/capstone-project#21]
### Value Description

As a User
I want to *bookmark the Sea Creatures I donated to the Museum*
so that *I can see my progress in the game*

### Description

<img width="316" alt="Screenshot 2022-05-24 at 10 08 53" src="https://user-images.githubusercontent.com/99614110/172225197-eb6ebafa-0202-43cd-a02c-55152931145a.png">

### Acceptance Criterea

- [ ] there should be a "donated" bookmark button on each ```SeaCreatureCard``` 
- [ ] there should be a "donated" bookmark button on each ```SeaCreatureDetailedCard```
- [ ] it should mark all sea creatures I donated
- [ ] there should be a counter on the top near the headline
- [ ] the "donated" bookmark button and its counter should have the same color and a different color than the caught bookmark button and counter

### Tasks

- [ ]  create a new branch
- [ ] create a ```IconButton```
- [ ] create a ```TotalCount``` component
- [ ] add styling
- [ ] add logic

### Complexity

 medium
