### ISSUE TITLE
Bookmark all the Fishes and Bugs that were donated and caught

### ISSUE THREAD

**Issue by cat-miller** [cat-miller/capstone-project#22]
### Value Description

As a User
I want to *bookmark the Fishes and Bugs I caught and donated to the Museum*
so that *I can see my progress in the game*

### Description

<img width="316" alt="Screenshot 2022-05-24 at 10 08 53" src="https://user-images.githubusercontent.com/99614110/172225197-eb6ebafa-0202-43cd-a02c-55152931145a.png">

### Acceptance Criterea

- [x] there should be a "caught" bookmark button and a "donated" bookmark button  on each ```FishCard``` and ```BugCard```
- [x] there should be a "caught" bookmark button and a "donated" bookmark button on each ```FishDetailedCard``` and ```BugDetailedCard```
- [x] it should mark all fish and bugs I caught and donated
- [x] there should be a counter on the top near the headline
- [x]  the "donated" bookmark button and its counter should have the same color and a different color than the "caught" bookmark button and "caught" counter

### Tasks

- [x]  create a new branch
- [x] create a ```IconButton```
- [x] create a ```TotalCount``` component
- [ ] add styling
- [x] add logic

### Complexity

medium
