### ISSUE TITLE
Overlay Neighbor List

### ISSUE THREAD

**Issue by cat-miller** [cat-miller/capstone-project#25]
### Value Statement

As a User
I want to *get an overlay list of all my 10 neighbors*
so that *I can choose which villager should be replaced when I select an eleventh neighbor.*

### Description
<img width="343" alt="Screenshot 2022-06-08 at 13 25 34" src="https://user-images.githubusercontent.com/99614110/172605084-75c9980d-8b72-4333-86db-2fabce21c5c0.png">

### Acceptance Criteria
- [ ] overlay list should pop up when neighbor array has 10 entries and user tries to choose an eleventh one.
- [ ] one should be able to choose which neighbor should be replaced by the new one
- [ ] there should be a close button so one can close the overlay without replacing any neighbor

### Tasks

- [ ] create a new branch
- [ ] create a ```NeighborIconList```
- [ ] make neighbor icons clickable
- [ ] logic for replacing neighbors

### Complexity

high
