### ISSUE TITLE
Bookmark buttons togglen

### ISSUE THREAD

**Issue by cat-miller** [cat-miller/capstone-project#26]
### Value Statement

As a User 
I want to * see a list of only the donated/caught critters when I click on the 'donated'/'caught' counter button*
so that *I can see my progress on the critter's page and focus only on the 'donated'/'caught'  critters*

### Description
<img width="316" alt="Screenshot 2022-05-24 at 10 08 53" src="https://user-images.githubusercontent.com/99614110/173250360-8d32c666-bc46-421e-8d38-9a2417215f8f.png">

### Acceptance Criteria

- [ ] on click donated or caught critters should only be displayed
- [ ] counter buttons should be clickable 
- [ ] counter buttons should change appearance when clicked

### Tasks

- [ ] create a new branch
- [ ] make counter clickable
- [ ] add logic to toggle lists onClick

### Complexity

low

**Comment by Luxa23** [comment]
hi @cat-miller,
sieht gut aus. Den zweiten Teil "and focus only on the 'donated'/'caught' critters" des "so that" kannst du, denk ich, weglassen.
