### ISSUE TITLE
Sort  Buttons

### ISSUE THREAD

**Issue by cat-miller** [cat-miller/capstone-project#27]
### Value Statement

As a User 
I want to *have sort buttons to sort critters or villagers by categories like price, alphabet, rarity or birthday*
so that *I can find certain critters or villagers faster*

### Description
<img width="322" alt="Screenshot 2022-06-13 at 16 59 18" src="https://user-images.githubusercontent.com/99614110/173383513-b33b24e8-bb00-46cb-813a-2dadd49e9f0b.png">

### Acceptance Criteria

- [x]  there should be clickable buttons to sort critters and villagers to sort by criterias like price or species
- [x] cards on pages should be sorted by those buttons onClick

### Tasks

- [x] create a new branch
- [x] create sort buttons
- [x] add logic to sort cards

### Complexity

low

**Comment by Luxa23** [comment]
Du könntest die US etwas kürzer halten und "like price, alphabet, rarity or birthday" weglassen. Das würde ich eher bei den AC erwähnen, da es hier um die User-Sicht geht. Mit dem zweiten Punkt bei den AC meinst du bestimmt, dass nur die Karten gezeigt werden, die nach dem Filter übrig bleiben oder? Sonst könnte man es auch so verstehen, dass die gefilterten Karten auch noch sortiert werden können. Dann wäre noch interessant, wie sortiert werden kann (A-Z, Z-A, usw.). 
Bei dem Select wäre es vielleicht ganz schön, wenn man Birthday, Species, Personality und jeweils den gewählten Wert gleichzeitig sehen könnte.
Wenn du Fragen hast, meld dich gerne.
