### ISSUE TITLE
Filter dropdown

### ISSUE THREAD

**Issue by cat-miller** [cat-miller/capstone-project#28]
### Value Statement

As a User
I want to *have a dropdown solution for personality and species on the VillagerPage*
so that *I can choose which personality or wich species I only want to be displayed on VillagerPage*

### Description
<img width="322" alt="Screenshot 2022-06-13 at 16 59 18" src="https://user-images.githubusercontent.com/99614110/173384814-cd5021e1-3889-4983-9b91-729b36383ebd.png">

### Acceptance Criteria

- [x] there should be a dropdown for personality
- [x] there should be a dropdown for species
- [x] list of cards should change according to the chosen criteria

### Tasks

- [x] create a new branch
- [x] create a dropdown for personality
- [x] create a dropdown for species
- [x] add logic to filter cards

### Complexity

low
