### ISSUE TITLE
Prorgress/OverviewButtons for critters on index

### ISSUE THREAD

**Issue by cat-miller** [cat-miller/capstone-project#29]
### Value Statement

As a User
I want to *have a List of progress buttons on my dashboard page*
so that I *have a quick overview of my progress*

### Description
![Screenshot 2022-06-16 at 14 38 25](https://user-images.githubusercontent.com/99614110/174071528-f1cdbbb3-6a96-4471-9f81-730365b4bf22.png)

### Acceptance Criteria
- [ ] there should be a list of progress buttons for each, the museum and what I caught
- [ ] buttons should be clickable and direct me to my donated or caught critters

### Tasks

- [ ]  create a new branch
- [ ] create a list with progress buttons
- [ ] add logic 

### Complexity

low
