### ISSUE TITLE
02. Create Detailed Overlay view(detailed Card) for Villagers

### ISSUE THREAD

**Issue by cat-miller** [cat-miller/capstone-project#3]
### Value Description / Statement

As a *user*
I want to be *able to click on the ```VillagerCards```*, so I can get a more *detailed version* of the villager I'm interested in.

### Description

<img width="319" alt="Screenshot 2022-05-24 at 10 08 16" src="https://user-images.githubusercontent.com/99614110/169985706-5523ccfa-552a-4895-b095-c21d4d4a3e3e.png">

### Acceptance Criteria

- [x]  cards in list should be clickable
- [x]  detailed card should  overlay the ```VillagersList```
- [x] detailed card should have a button to close the overlay view
- [x] detailed card should display the picture of the villager quite big ( little more than have of the card (see description)
- [x] there should be a 'bubble' with the individual catch-phrase of  the villager positioned nearby the head
- [x] detailed card should have the villager's name  as heading below the picture
- [x] detailed card should contain personality 
- [x] detailed card should contain species
- [x] detailed card should contain gender
- [x] detailed card should contain birthday
- [x] ```VillagersList``` in background should be at a transparency of 30% when ```DetailedVillagerCard``` is displayed in overview 

( bookmark buttons on the bottom right corner of the card will be implemented by me when I implement the the bookmark logic )

### Tasks

- [x] create a new branch
- [x] create a component ```DetailedVillagerCard```
- [x] make ```VillagerCards``` clickable
- [x] implement overlay view for detailed view
- [x] make sure both cards, ```VillagerCard``` and ```DetailedVillagerCard``` have the same color

### Complexity

medium

**Comment by marcbendixen** [comment]
Hey 👋 
for me this is a very good user story 👍  well done.

There is only one thing i want to mention here: making die details view as an overlay could be a bit more complex for a future feature, like "linking to a details page". Because that way you don't have a direct url-route to the view. Just keep that in mind 🙂
