### ISSUE TITLE
Passport on Dashbaord page

### ISSUE THREAD

**Issue by cat-miller** [cat-miller/capstone-project#30]
### Value Statement

As a User
I want to *have a 'Passport' form where I can put all my informations concerning my island*
so that *can save them on one place and send them to other gamers for exchange*

### Description
![Screenshot 2022-06-16 at 14 38 25](https://user-images.githubusercontent.com/99614110/174071666-7d2bbe3d-c475-4752-90de-18827738f75c.png)

### Acceptance Criteria

- [ ] there should be a passport form on the dashboard page 
- [ ] it should have inputs for [ ] my name [ ] island name [ ] native fruit [ ] hemisphere [ ] switch code [ ] dream id [ ] creator id
- [ ] passport should be clickable 
- [ ] onClick there should be a slug page where you can send someone the link from

### Tasks

- [ ] create a new branch
- [ ] create a Passport component
- [ ] ad logic for validating the form
- [ ] save information to backend
- [ ] build a slug page for passport
- [ ] make passport clickable

### Complexity

medium

**Comment by Chaosfuchs** [comment]
LGTM 🚀  :)
