### ISSUE TITLE
Theme Icon radio button bar on index page

### ISSUE THREAD

**Issue by cat-miller** [cat-miller/capstone-project#31]
### Value Statement

As a User 
I want to *have  the opportunity to chose from different themes*
so that *I can customize the appearance of my app*

### Description
![Screenshot 2022-06-16 at 14 22 01](https://user-images.githubusercontent.com/99614110/174068832-ad3d6ccf-1fcb-4f54-a096-6783f243bac3.png)

### Acceptance Criteria

- [ ] there should be a list of icons on the dashboard page
- [ ] the icon should show the theme
- [ ] icons should be clickable 
- [ ] onClick the appearance of the app should change

### Tasks

- [ ] create a new branch
- [ ] create a list of theme icons
- [ ] add logic
- [ ] add themes

### Complexity

low
