### ISSUE TITLE
User Login via github

### ISSUE THREAD

**Issue by cat-miller** [cat-miller/capstone-project#33]
### Value Statement

As a User
I want to *login via github*
so that *I have all my informations on my user account*

### Acceptance Criteria

- [ ] there should be a landing page with the option to login via github
- [ ] my user account should be saved to the backend

### Tasks

- [ ] create a new branch
- [ ] login page on index page, dashboard page on dashboard page
- [ ] add logic for logic

### Complexity
medium
