### ISSUE TITLE
05. Add Navigation and Heading to the App

### ISSUE THREAD

**Issue by cat-miller** [cat-miller/capstone-project#5]
### Value Description / Statement

As a *user*
I want to have a *navigation to navigate to the several pages*. I also want a *page heading so I can read on wich page I am, when I navigate.*

### Description

<img width="310" alt="Screenshot 2022-05-24 at 10 08 30" src="https://user-images.githubusercontent.com/99614110/170030032-85204f7a-d16f-40b6-bfbd-2ec2c8796a63.png">

<img width="316" alt="Screenshot 2022-05-24 at 10 08 53" src="https://user-images.githubusercontent.com/99614110/170030062-0fdf2fff-66ba-4bf8-9297-d7887c4e5b3f.png">

### Acceptance Criteria

- [x] there should be a headline on the upper part of each page, that tells the page's title
- [x] there should be a ```Navigation``` on bottom of each page
- [x] above the navigation there should be a light gradient so the content looks as if it would fade out behind the navigation
- [x] the background of the active icon should be highlighted in a darker shade of the navigation's color

( the buttons on the top left and right, that show how many critters were collected or donated to the museum will be implemented by me when I implement the logic for this bookmarks)

### Tasks

- [x] create a new branch
- [x] create a component ```Navigation```
- [x] link all pages with the ```Navigation```

### Complexity

low

**Comment by CJAkkuec** [comment]
Looks good, just one minor note:

>  link all pages with the Navigation
If the pages already have content, then that's great - but you should avoid linking to "empty pages" in your deployments. Usually you would only link to pages that currently have any content to be displayed, even if that seems counter-productive in terms of creating the navbar. So if you only have two pages with content at present, your navbar (at this point) would only include two icons, etc.
