### ISSUE TITLE
06. Add Theming (Dark/ Light mode)

### ISSUE THREAD

**Issue by cat-miller** [cat-miller/capstone-project#6]
### Value Description / Statement
As a *user*
I want to have *an option on my ```DashboardPage``` where I can choose different themes for my app.*

### Description

For starters there should be a light and a dark mode, (the light mode in this case could be the spring theme inspired by the cherry-blossom season and the dark one could be the autumn theme inspired by the beloved Halloween season) Later on there could be themes for the 4 seasons, the cherry blossom theme, the Halloween theme, the Christmas theme, the carnival theme... and so on.

### Acceptance Criteria
- [ ] there should be a button that toggles or a dropdown solution to select light or dark mode on the ```DashboardPage```
- [ ] there should be a light theme and a dark theme

### Tasks

- [ ] create a new branch
- [ ] create a component to select the theme
- [ ] create  2 themes 
- [ ] implement theming

### Complexity

medium

**Comment by CJAkkuec** [comment]
As a user story, this is perfectly fine - I'm just not sure if you'd implement this feature at this point. This feels rather more like a "bonus feature" once your MVP is completed.
