### ISSUE TITLE
04. Fetch bugs and sea creatures

### ISSUE THREAD

**Issue by cat-miller** [cat-miller/capstone-project#9]
### Value Description / Statement

As a *user*
I want to *see all fishes of Animal Crossing displayed as a list of ```CritterCards``` on a ```FishPage```*. So that I can look up all information about the fishes I can catch in the game.  The cards should *be clickable* so I can get *more details in the ```DetailedCrittersCard``` on overlay.*

### Description

<img width="325" alt="Screenshot 2022-05-24 at 11 10 34" src="https://user-images.githubusercontent.com/99614110/169995731-d8a7f340-7b97-4f5d-9218-0107b74ec4ad.png">

### Acceptance Criteria

- [ ]  there should be a ```FishPage```
- [ ]  fishes should be displayed as a list of ```CritterCards``` on the ```FishPage```.
- [ ] a picture of the given critter should be displayed on the ```CritterCard``` 
- [ ] the critter's name should be displayed on the card as a heading
- [ ] the location, where to find it, should be displayed on the ```CritterCard```
- [ ] the size of the shadow should be displayed on the ```CritterCard```
- [ ] the cards should be clickable
- [ ] there should be a ```DetailedCrittersCard``` on overlay likewise the ```DetailedVillagerCard```
- [ ] the ```DetailedCrittersCard``` should display [ ] name, [ ] availability, [ ] location, [ ] rarity, [ ] shadow, [ ] price, [ ] price-cj 

( bookmarks shown in description picture will be implemented by me when I implement the logic for bookmarks )

### Tasks

- [ ] create a new branch
- [ ] fetch data for fishes from ACNH API
- [ ] create component ```CrittersCard```
- [ ] create component ```DetailedCrittersCard```
- [ ] if needed create separate card components like ```FishCard``` , ```DetailedFishCard```
- [ ] create ```FishPage``` 

### Complexity

low - medium

**Comment by Morten-Moeller** [comment]
Looks good to me, you might consider if navigation is more important to the user than having more pages.
